#!/bin/bash
# /usr/bin/blurlock

# take screenshot
import -window root /tmp/screenshot.png

# blur it
convert /tmp/screenshot.png -blur 0x5 /tmp/screenshotblur.png
rm /tmp/screenshot.png

xset dpms 15
# lock the screen
i3lock -n -i /tmp/screenshotblur.png
xset dpms 0


# sleep 1 adds a small delay to prevent possible race conditions with suspend
sleep 1

exit 0
